version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes: 
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  express-js:
    build: ./shopping.com/Dockerfile #local Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb

volumes: 
  mongodb-data: